services:
  db_node1:
    image: couchbase:latest
    container_name: db_node1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "11210:11210"
      - "11207:11207"
      - "11211:11211"
    networks:
      - databases
    volumes:
      - ./dataset:/dataset
  db_node2:
    image: couchbase:latest
    container_name: db_node2
    ports:
      - "8093:8091"
      - "8094:8092"
      - "11212:11210"
      - "11208:11207"
      - "11213:11211"
    networks:
      - databases
  db_node3:
    image: couchbase:latest
    container_name: db_node3
    ports:
      - "8095:8091"
      - "8096:8092"
      - "11214:11210"
      - "11209:11207"
      - "11215:11211"
    networks:
      - databases

networks:
  databases:
    driver: bridge
  